export const FETCH_ALBUMS = "FETCH_ALBUMS";
export const FILTER_ALBUMS_BY_ARTIST = "FILTER_ALBUMS_BY_ARTIST";
export const FILTER_ALBUMS_BY_GENRE = "FILTER_ALBUMS_BY_GENRE";
export const ORDER_ALBUMS_BY_PRICE = "FILTER_ALBUMS_BY_PRICE";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
